/* js/data.js — Built-in plant database (metric: spacing in cm)
   ================================================================ */

'use strict';

// Each plant:
//   id, name, emoji, cat (vegetable|herb|fruit|flower)
//   spacing: 'WCm×HCm' — the plant's own footprint (space taken by one plant).
//            Drives the grid block size. Small plants (<10 cm) get density >1
//            shown as "×N" in the bed grid (N = floor(10/w)*floor(10/h)).
//   rowSpacing: informational gap in cm between rows. Displayed in UI metadata,
//            but not used in automatic plant count calculations.
//   cellsNeeded: approximate grid cells the plant block occupies (informational)
//   family: botanical family — assigned via PLANT_FAMILIES map below
//   sun: 'full' | 'partial' | 'shade'
//   water: 'low' | 'medium' | 'high'
//   height: 'low' | 'medium' | 'tall' | 'vine'
//   daysToHarvest: string
//   sowIndoor:  months (1-based) to start seeds indoors / under cover (null = not applicable)
//   sowOutdoor: months to sow directly outside or transplant outdoors
//   harv: months to harvest
//   good: companion plant ids (benefits)
//   bad:  companion plant ids (allelopathy / pests)
//   notes: short growing tip

// Half-month helper: H('3-6') → [3,3.5,…,6,6.5]  H('3,7-8') → [3,3.5,7,7.5,8,8.5]
// Whole integer endpoint includes both halves of that month.
function H(str) {
  const result = new Set();
  for (const token of (str || '').split(',')) {
    const t = token.trim();
    if (!t) continue;
    const parts = t.split('-');
    if (parts.length === 2) {
      const from = parseFloat(parts[0]);
      const to   = parseFloat(parts[1]);
      const end  = Number.isInteger(to) ? to + 0.5 : to;
      for (let h = from; h <= end + 1e-9; h = Math.round((h + 0.5) * 10) / 10) result.add(h);
    } else {
      const v = parseFloat(t);
      if (Number.isInteger(v)) { result.add(v); result.add(v + 0.5); }
      else result.add(v);
    }
  }
  return [...result].sort((a, b) => a - b);
}

const BUILTIN_PLANTS = [
  // ── VEGETABLES ──
  { id:'tomato',        name:'Tomato',           emoji:'🍅', cat:'vegetable', spacing:'60×60', cellsNeeded:1, sun:'full',    water:'medium', height:'tall',  daysToHarvest:'70–85',
    sowIndoor:H('3-4'),      sowOutdoor:H('5-6'),      harv:H('7-9'),
    good:['basil','carrot','marigold','parsley','borage','chive'], bad:['fennel','potato'],
    notes:'Stake early. Pinch suckers for bigger fruit. Keep foliage dry.' },
  { id:'cherry_tomato', name:'Cherry Tomato',    emoji:'🍅', cat:'vegetable', spacing:'50×50', cellsNeeded:1, sun:'full',    water:'medium', height:'tall',  daysToHarvest:'55–70',
    sowIndoor:H('3-4'),      sowOutdoor:H('5-6'),      harv:H('7-10'),
    good:['basil','carrot','marigold','parsley'], bad:['fennel','potato'],
    notes:'More disease-resistant than large tomatoes. Prolific producer.' },
  { id:'pepper',        name:'Bell Pepper',      emoji:'🫑', cat:'vegetable', spacing:'45×45', cellsNeeded:1, sun:'full',    water:'medium', height:'medium',daysToHarvest:'70–90',
    sowIndoor:H('2-3'),      sowOutdoor:H('5-6'),      harv:H('7-9'),
    good:['basil','carrot','tomato','marigold'], bad:['fennel'],
    notes:'Needs warm soil (>15 °C). Harvest green or wait for full colour.' },
  { id:'hot_pepper',    name:'Hot Pepper',       emoji:'🌶️', cat:'vegetable', spacing:'40×40', cellsNeeded:1, sun:'full',    water:'low',    height:'medium',daysToHarvest:'70–100',
    sowIndoor:H('2-3'),      sowOutdoor:H('5-6'),      harv:H('7-10'),
    good:['basil','carrot','tomato'], bad:['fennel'],
    notes:'Hotter varieties need less water. Great in containers.' },
  { id:'cucumber',      name:'Cucumber',         emoji:'🥒', cat:'vegetable', spacing:'50×50', cellsNeeded:1, sun:'full',    water:'high',   height:'vine',  daysToHarvest:'50–70',
    sowIndoor:H('4-5'),      sowOutdoor:H('5-6'),      harv:H('7-9'),
    good:['bean_bush','dill','corn','sunflower','marigold','nasturtium'], bad:['potato','sage','fennel'],
    notes:'Train on a trellis to save space. Harvest often for continuous production.' },
  { id:'zucchini',      name:'Courgette',        emoji:'🥒', cat:'vegetable', spacing:'90×90', cellsNeeded:4, sun:'full',    water:'medium', height:'medium',daysToHarvest:'45–55',
    sowIndoor:H('4-5'),      sowOutdoor:H('5-6'),      harv:H('7-9'),
    good:['corn','bean_bush','marigold','nasturtium'], bad:['potato','fennel'],
    notes:'Harvest young (15–20 cm) for best flavour. Plants become very large.' },
  { id:'squash',        name:'Butternut Squash', emoji:'🎃', cat:'vegetable', spacing:'100×100',cellsNeeded:4,sun:'full',    water:'medium', height:'vine',  daysToHarvest:'80–100',
    sowIndoor:H('4-5'),      sowOutdoor:H('5-6'),      harv:H('9-10'),
    good:['corn','bean_bush','marigold','nasturtium'], bad:['potato','fennel'],
    notes:'Harvest when tan. Stores months in a cool dry place.' },
  { id:'pumpkin',       name:'Pumpkin',          emoji:'🎃', cat:'vegetable', spacing:'150×150',cellsNeeded:4,sun:'full',    water:'medium', height:'vine',  daysToHarvest:'85–125',
    sowIndoor:H('5-6'),      sowOutdoor:H('6'),        harv:H('9-10'),
    good:['corn','bean_bush','marigold','nasturtium'], bad:['potato'],
    notes:'Needs lots of space. Classic "Three Sisters" planting.' },
  { id:'lettuce',       name:'Lettuce',          emoji:'🥬', cat:'vegetable', spacing:'25×25', cellsNeeded:1, sun:'partial', water:'medium', height:'low',   daysToHarvest:'30–60',
    sowIndoor:H('2-3,8-9'),  sowOutdoor:H('3-4,9-10'), harv:H('4-6,10-11'),
    good:['carrot','radish','strawberry','chive','dill'], bad:[],
    notes:'Cut-and-come-again. Bolt-resistant varieties for summer.' },
  { id:'spinach',       name:'Spinach',          emoji:'🥬', cat:'vegetable', spacing:'10×10', rowSpacing:15, cellsNeeded:1, sun:'partial', water:'medium', height:'low',   daysToHarvest:'40–50',
    sowIndoor:H('2-3,8-9'),  sowOutdoor:H('3-4,9-10'), harv:H('4-5,9-11'),
    good:['strawberry','pea','bean_bush','radish'], bad:['fennel'],
    notes:'Cool-season. Plant in shade of taller plants in summer.' },
  { id:'kale',          name:'Kale',             emoji:'🥬', cat:'vegetable', spacing:'50×50', cellsNeeded:1, sun:'full',    water:'medium', height:'medium',daysToHarvest:'55–65',
    sowIndoor:H('3,7-8'),    sowOutdoor:H('4,8-9'),    harv:H('5-7,10-12'),
    good:['beet','celery','onion'], bad:['tomato','strawberry','bean_bush'],
    notes:'Frost-tolerant. Flavour improves after frost.' },
  { id:'arugula',       name:'Arugula',          emoji:'🥬', cat:'vegetable', spacing:'10×10', rowSpacing:15, cellsNeeded:1, sun:'partial', water:'medium', height:'low',   daysToHarvest:'25–40',
    sowIndoor:H('3-4,8-9'),  sowOutdoor:H('4,9'),      harv:H('4-5,9-11'),
    good:['pea','bean_bush','carrot'], bad:[],
    notes:'Peppery flavour intensifies with age. Bolts in heat — re-sow often.' },
  { id:'carrot',        name:'Carrot',           emoji:'🥕', cat:'vegetable', spacing:'10×10', rowSpacing:15, cellsNeeded:1, sun:'full',    water:'medium', height:'low',   daysToHarvest:'70–80',
    sowIndoor:null,          sowOutdoor:H('3-4,7-8'),  harv:H('6-7,10-11'),
    good:['lettuce','chive','rosemary','tomato','bean_bush'], bad:['dill','fennel'],
    notes:'Direct sow only. Loose, deep soil essential. Thin seedlings carefully.' },
  { id:'radish',        name:'Radish',           emoji:'🌱', cat:'vegetable', spacing:'10×10', rowSpacing:15, cellsNeeded:1, sun:'full',    water:'medium', height:'low',   daysToHarvest:'22–30',
    sowIndoor:null,          sowOutdoor:H('3-4,8-9'),  harv:H('4-5,9-10'),
    good:['carrot','cucumber','lettuce','pea','nasturtium'], bad:[],
    notes:'Fastest vegetable to harvest. Great for marking slower rows.' },
  { id:'beet',          name:'Beet',             emoji:'🫐', cat:'vegetable', spacing:'10×10', rowSpacing:20, cellsNeeded:1, sun:'full',    water:'medium', height:'low',   daysToHarvest:'55–70',
    sowIndoor:null,          sowOutdoor:H('3-4,7-8'),  harv:H('6-7,10-11'),
    good:['lettuce','onion','bean_bush','radish'], bad:['corn','tomato'],
    notes:'Both roots and greens are edible. Thin ruthlessly for large roots.' },
  { id:'broccoli',      name:'Broccoli',         emoji:'🥦', cat:'vegetable', spacing:'60×60', cellsNeeded:1, sun:'full',    water:'medium', height:'medium',daysToHarvest:'70–100',
    sowIndoor:H('2-3,7'),    sowOutdoor:H('3-4,8'),    harv:H('5-6,10-11'),
    good:['celery','dill','onion','rosemary','marigold'], bad:['tomato','pepper','strawberry'],
    notes:'Harvest central head before flowering. Side shoots keep producing.' },
  { id:'cauliflower',   name:'Cauliflower',      emoji:'🥦', cat:'vegetable', spacing:'60×60', cellsNeeded:1, sun:'full',    water:'medium', height:'medium',daysToHarvest:'70–80',
    sowIndoor:H('2-3,7'),    sowOutdoor:H('3-4,8'),    harv:H('5-6,10-11'),
    good:['celery','dill','onion','rosemary'], bad:['tomato','pepper','strawberry'],
    notes:'Tie leaves over head to keep it white (blanching).' },
  { id:'cabbage',       name:'Cabbage',          emoji:'🥬', cat:'vegetable', spacing:'60×60', cellsNeeded:1, sun:'full',    water:'medium', height:'medium',daysToHarvest:'70–120',
    sowIndoor:H('2-3,7'),    sowOutdoor:H('3-4,8'),    harv:H('5-6,10-11'),
    good:['celery','dill','onion','mint','chamomile'], bad:['tomato','strawberry'],
    notes:'Frost-tolerant. Water consistently to prevent heads splitting.' },
  { id:'onion',         name:'Onion',            emoji:'🧅', cat:'vegetable', spacing:'10×10', rowSpacing:25, cellsNeeded:1, sun:'full',    water:'medium', height:'medium',daysToHarvest:'100–120',
    sowIndoor:H('1-2'),      sowOutdoor:H('3-4'),      harv:H('7-8'),
    good:['carrot','lettuce','tomato','beet','chamomile'], bad:['pea','bean_bush'],
    notes:'Harvest when tops fall over. Cure in warm dry place before storing.' },
  { id:'garlic',        name:'Garlic',           emoji:'🧄', cat:'vegetable', spacing:'10×10', rowSpacing:25, cellsNeeded:1, sun:'full',    water:'low',    height:'medium',daysToHarvest:'220–240',
    sowIndoor:null,          sowOutdoor:H('10-11'),    harv:H('6-7'),
    good:['tomato','pepper','carrot'], bad:['pea','bean_bush'],
    notes:'Plant cloves in autumn. Harvest when lower leaves brown. Natural pest repellent.' },
  { id:'leek',          name:'Leek',             emoji:'🧅', cat:'vegetable', spacing:'15×15', rowSpacing:20, cellsNeeded:1, sun:'full',    water:'medium', height:'tall',  daysToHarvest:'100–130',
    sowIndoor:H('1-3'),      sowOutdoor:H('4-5'),      harv:H('9-12'),
    good:['carrot','celery'], bad:['pea','bean_bush'],
    notes:'Mound soil around stem to blanch. Very hardy, survives hard frosts.' },
  { id:'bean_bush',     name:'Bush Bean',        emoji:'🫘', cat:'vegetable', spacing:'20×20', cellsNeeded:1, sun:'full',    water:'medium', height:'low',   daysToHarvest:'50–60',
    sowIndoor:null,          sowOutdoor:H('4-6'),      harv:H('7-9'),
    good:['carrot','cucumber','strawberry','corn','potato','nasturtium'], bad:['onion','garlic','fennel'],
    notes:'Nitrogen fixer. Succession plant every 2 weeks.' },
  { id:'bean_pole',     name:'Pole Bean',        emoji:'🫘', cat:'vegetable', spacing:'20×20', rowSpacing:30, cellsNeeded:1, sun:'full',    water:'medium', height:'tall',  daysToHarvest:'60–70',
    sowIndoor:null,          sowOutdoor:H('4-5'),      harv:H('7-10'),
    good:['carrot','cucumber','corn','squash'], bad:['onion','garlic','fennel'],
    notes:'Needs trellis or poles. Produces all season long.' },
  { id:'pea',           name:'Sugar Snap Pea',   emoji:'🫛', cat:'vegetable', spacing:'10×10', rowSpacing:20, cellsNeeded:1, sun:'full',    water:'medium', height:'vine',  daysToHarvest:'55–70',
    sowIndoor:null,          sowOutdoor:H('2-3,9-10'), harv:H('5-6,11-12'),
    good:['carrot','radish','mint','corn'], bad:['onion','garlic','chive'],
    notes:'Cool-season nitrogen fixer. Plant in early spring or autumn.' },
  { id:'corn',          name:'Sweet Corn',       emoji:'🌽', cat:'vegetable', spacing:'35×35', cellsNeeded:1, sun:'full',    water:'high',   height:'tall',  daysToHarvest:'60–100',
    sowIndoor:null,          sowOutdoor:H('4-5'),      harv:H('8-9'),
    good:['bean_bush','squash','cucumber','sunflower'], bad:['tomato','celery'],
    notes:'Wind-pollinated — plant in blocks of at least 4×4.' },
  { id:'potato',        name:'Potato',           emoji:'🥔', cat:'vegetable', spacing:'35×35', rowSpacing:70, cellsNeeded:1, sun:'full',    water:'medium', height:'medium',daysToHarvest:'70–120',
    sowIndoor:null,          sowOutdoor:H('3-4'),      harv:H('7-9'),
    good:['bean_bush','corn','marigold'], bad:['tomato','sunflower','fennel','carrot'],
    notes:'Hill up soil as plant grows. Rotate location each year.' },
  { id:'eggplant',      name:'Eggplant',         emoji:'🍆', cat:'vegetable', spacing:'60×60', cellsNeeded:1, sun:'full',    water:'medium', height:'medium',daysToHarvest:'65–80',
    sowIndoor:H('2-3'),      sowOutdoor:H('5-6'),      harv:H('7-9'),
    good:['basil','pepper','tomato','marigold'], bad:['fennel'],
    notes:'Loves heat. Harvest while glossy — dull skin means overripe.' },
  { id:'asparagus',     name:'Asparagus',        emoji:'🌿', cat:'vegetable', spacing:'45×45', cellsNeeded:1, sun:'full',    water:'medium', height:'tall',  daysToHarvest:'730+',
    sowIndoor:null,          sowOutdoor:H('3-4'),      harv:H('4-5'),
    perennial:true, dormant:H('8-12,1-2'),
    good:['tomato','parsley','basil','marigold'], bad:['onion','garlic','potato'],
    notes:'Perennial. Do not harvest first 2 years. Lives 20+ years.' },
  { id:'broad_bean',    name:'Broad Bean',       emoji:'🫘', cat:'vegetable', spacing:'25×25', rowSpacing:25, cellsNeeded:1, sun:'full',    water:'medium', height:'tall',  daysToHarvest:'90–100',
    sowIndoor:null,          sowOutdoor:H('10-11,2-3'),harv:H('5-7'),
    good:['spinach','potato','beet','carrot','kale'], bad:['onion','garlic'],
    notes:'Autumn-sown plants produce heavier crops. Pinch out shoot tips to deter blackfly.' },
  { id:'runner_bean',   name:'Runner Bean',      emoji:'🫘', cat:'vegetable', spacing:'25×25', rowSpacing:45, cellsNeeded:1, sun:'full',    water:'high',   height:'vine',  daysToHarvest:'60–70',
    sowIndoor:null,          sowOutdoor:H('4-5'),      harv:H('7-10'),
    good:['carrot','cucumber','corn','squash','nasturtium'], bad:['onion','garlic','fennel'],
    notes:'Needs trellis or poles (2m+). Keep picking for continuous pods. Never let pods dry on the plant.' },
  { id:'brussels_sprout',name:'Brussels Sprout', emoji:'🥦', cat:'vegetable', spacing:'60×60', cellsNeeded:1, sun:'full',    water:'medium', height:'tall',  daysToHarvest:'100–130',
    sowIndoor:H('3-4'),      sowOutdoor:H('5-6'),      harv:H('10-12,1-2'),
    good:['celery','dill','onion','rosemary','marigold','nasturtium'], bad:['tomato','pepper','strawberry'],
    notes:'Firm soil and staking essential in exposed sites. Flavour improves after frost.' },
  { id:'chard',         name:'Chard',            emoji:'🥬', cat:'vegetable', spacing:'30×30', cellsNeeded:1, sun:'partial', water:'medium', height:'medium',daysToHarvest:'50–60',
    sowIndoor:H('3-4,7-8'),  sowOutdoor:H('4-5,8-9'), harv:H('5-11'),
    good:['bean_bush','lettuce','onion','beet'], bad:['corn','potato'],
    notes:'Cut-and-come-again leaves and stems. Very frost-tolerant for a long harvest season.' },
  { id:'celery',        name:'Celery',           emoji:'🥬', cat:'vegetable', spacing:'30×30', cellsNeeded:1, sun:'partial', water:'high',   height:'medium',daysToHarvest:'100–130',
    sowIndoor:H('2-3'),      sowOutdoor:H('5-6'),      harv:H('8-11'),
    good:['tomato','bean_bush','cabbage','leek','onion'], bad:['carrot','corn'],
    notes:'Needs consistently moist, fertile soil. Self-blanching varieties avoid the need to earth up.' },
  { id:'kohlrabi',      name:'Kohl Rabi',        emoji:'🌱', cat:'vegetable', spacing:'25×25', cellsNeeded:1, sun:'full',    water:'medium', height:'low',   daysToHarvest:'55–70',
    sowIndoor:H('3-4,7-8'),  sowOutdoor:H('4-5,8'),   harv:H('5-6,9-11'),
    good:['bean_bush','beet','onion','celery'], bad:['tomato','pepper','strawberry'],
    notes:'Harvest at golf-ball to tennis-ball size for sweetest flavour. Leaves also edible.' },
  { id:'mangetout',     name:'Mangetout',        emoji:'🫛', cat:'vegetable', spacing:'10×10', rowSpacing:20, cellsNeeded:1, sun:'full',    water:'medium', height:'vine',  daysToHarvest:'60–70',
    sowIndoor:null,          sowOutdoor:H('2-3,9-10'), harv:H('5-7,11-12'),
    good:['carrot','radish','mint','corn'], bad:['onion','garlic','chive'],
    notes:'Flat pods eaten whole before peas develop. Cool-season nitrogen fixer. Needs trellis support.' },
  { id:'pak_choi',      name:'Pak Choi',         emoji:'🥬', cat:'vegetable', spacing:'25×25', cellsNeeded:1, sun:'partial', water:'high',   height:'low',   daysToHarvest:'30–50',
    sowIndoor:H('3-4,7-8'),  sowOutdoor:H('4-5,8-9'), harv:H('5-6,9-10'),
    good:['carrot','celery','bean_bush'], bad:['tomato','strawberry'],
    notes:'Bolts in heat — best crops in spring and autumn. Both leaves and stems edible.' },
  { id:'parsnip',       name:'Parsnip',          emoji:'🌱', cat:'vegetable', spacing:'10×10', rowSpacing:30, cellsNeeded:1, sun:'full',    water:'low',    height:'low',   daysToHarvest:'110–120',
    sowIndoor:null,          sowOutdoor:H('2-4'),      harv:H('10-12,1-2'),
    good:['pea','bean_bush','lettuce','radish'], bad:['carrot'],
    notes:'Direct sow only — does not transplant. Very slow to germinate. Flavour sweetens after frost.' },
  { id:'shallot',       name:'Shallot',          emoji:'🧅', cat:'vegetable', spacing:'15×15', rowSpacing:25, cellsNeeded:1, sun:'full',    water:'low',    height:'medium',daysToHarvest:'90–100',
    sowIndoor:null,          sowOutdoor:H('2-3'),      harv:H('7-8'),
    good:['carrot','tomato','beet','chamomile'], bad:['pea','bean_bush'],
    notes:'Plant sets tip-upward, just showing above soil. Each set multiplies into a cluster of bulbs.' },
  { id:'sweet_potato',  name:'Sweet Potato',     emoji:'🍠', cat:'vegetable', spacing:'40×40', rowSpacing:75, cellsNeeded:1, sun:'full',    water:'medium', height:'vine',  daysToHarvest:'90–120',
    sowIndoor:null,          sowOutdoor:H('5-6'),      harv:H('9-10'),
    good:['bean_bush','corn','marigold'], bad:['squash'],
    notes:'Needs warm soil (>18 °C). Plant slips after last frost. Vines can be trained to save space.' },
  { id:'swede',         name:'Swede',            emoji:'🌱', cat:'vegetable', spacing:'25×25', cellsNeeded:1, sun:'full',    water:'medium', height:'low',   daysToHarvest:'120–150',
    sowIndoor:null,          sowOutdoor:H('5-6'),      harv:H('10-12,1-2'),
    good:['pea','bean_bush','onion','leek'], bad:['tomato','strawberry'],
    notes:'Direct sow only. Frost improves flavour. Can leave in ground through winter as natural storage.' },
  { id:'turnip',        name:'Turnip',           emoji:'🌱', cat:'vegetable', spacing:'15×15', cellsNeeded:1, sun:'full',    water:'medium', height:'low',   daysToHarvest:'40–70',
    sowIndoor:null,          sowOutdoor:H('2-3,7-8'),  harv:H('4-5,9-11'),
    good:['pea','bean_bush','nasturtium'], bad:['tomato','strawberry'],
    notes:'Harvest small (golf-ball size) for best flavour. Spring and autumn crops. Tops also edible.' },

  // ── HERBS ──
  { id:'basil',         name:'Basil',            emoji:'🌿', cat:'herb',      spacing:'30×30', cellsNeeded:1, sun:'full',    water:'medium', height:'medium',daysToHarvest:'24–28',
    sowIndoor:H('4-5'),      sowOutdoor:H('5-6'),      harv:H('6-9'),
    good:['tomato','pepper','asparagus','oregano','eggplant'], bad:['sage','fennel'],
    notes:'Pinch flowers to extend harvest. Best companion for tomatoes.' },
  { id:'parsley',       name:'Parsley',          emoji:'🌿', cat:'herb',      spacing:'25×25', cellsNeeded:1, sun:'partial', water:'medium', height:'low',   daysToHarvest:'70–90',
    sowIndoor:H('2-3,8-9'),  sowOutdoor:H('3-4'),      harv:H('5-10'),
    good:['tomato','asparagus','corn','carrot'], bad:['onion'],
    notes:'Biennial. Soak seeds overnight before planting. Slow to germinate.' },
  { id:'cilantro',      name:'Cilantro',         emoji:'🌿', cat:'herb',      spacing:'15×15', cellsNeeded:1, sun:'partial', water:'medium', height:'low',   daysToHarvest:'45–60',
    sowIndoor:null,          sowOutdoor:H('3-4,8-9'),  harv:H('5-6,9-10'),
    good:['spinach','tomato','pea','bean_bush'], bad:['fennel'],
    notes:'Bolts quickly in heat. Succession sow every few weeks.' },
  { id:'dill',          name:'Dill',             emoji:'🌿', cat:'herb',      spacing:'30×30', cellsNeeded:1, sun:'full',    water:'low',    height:'tall',  daysToHarvest:'40–60',
    sowIndoor:null,          sowOutdoor:H('4-6'),      harv:H('6-9'),
    good:['cabbage','cucumber','lettuce','onion'], bad:['tomato','carrot','fennel','pepper'],
    notes:'Direct sow only. Self-seeds readily. Attracts beneficial insects.' },
  { id:'fennel',        name:'Fennel',           emoji:'🌿', cat:'herb',      spacing:'50×50', cellsNeeded:1, sun:'full',    water:'low',    height:'tall',  daysToHarvest:'65–90',
    sowIndoor:H('4-5'),      sowOutdoor:H('5'),        harv:H('7-9'),
    good:['dill'], bad:['tomato','pepper','bean_bush','carrot','potato','cucumber','eggplant'],
    notes:'Allelopathic! Plant well away from most vegetables.' },
  { id:'rosemary',      name:'Rosemary',         emoji:'🌿', cat:'herb',      spacing:'60×60', cellsNeeded:1, sun:'full',    water:'low',    height:'medium',daysToHarvest:'80–180',
    sowIndoor:null,          sowOutdoor:H('4-5'),      harv:H('1-12'),
    perennial:true, dormant:[],
    good:['bean_bush','cabbage','carrot','sage'], bad:['cucumber'],
    notes:'Perennial in mild climates. Drought-tolerant once established.' },
  { id:'thyme',         name:'Thyme',            emoji:'🌿', cat:'herb',      spacing:'30×30', cellsNeeded:1, sun:'full',    water:'low',    height:'low',   daysToHarvest:'85–90',
    sowIndoor:H('3-4'),      sowOutdoor:H('4-5'),      harv:H('5-10'),
    perennial:true, dormant:[],
    good:['tomato','eggplant','strawberry','cabbage'], bad:['cucumber'],
    notes:'Perennial. Drought-tolerant. Best flavour just before flowering.' },
  { id:'oregano',       name:'Oregano',          emoji:'🌿', cat:'herb',      spacing:'30×30', cellsNeeded:1, sun:'full',    water:'low',    height:'low',   daysToHarvest:'80–90',
    sowIndoor:H('3-4'),      sowOutdoor:H('4-5'),      harv:H('5-10'),
    perennial:true, dormant:[],
    good:['tomato','pepper','asparagus','squash'], bad:['cucumber'],
    notes:'Perennial. Flavour best just before flowering. Repels aphids.' },
  { id:'sage',          name:'Sage',             emoji:'🌿', cat:'herb',      spacing:'50×50', cellsNeeded:1, sun:'full',    water:'low',    height:'medium',daysToHarvest:'75–80',
    sowIndoor:null,          sowOutdoor:H('4-5'),      harv:H('5-10'),
    perennial:true, dormant:[],
    good:['rosemary','carrot','cabbage','tomato'], bad:['cucumber','basil'],
    notes:'Perennial. Repels cabbage moths and aphids.' },
  { id:'mint',          name:'Mint',             emoji:'🌿', cat:'herb',      spacing:'30×30', cellsNeeded:1, sun:'partial', water:'medium', height:'low',   daysToHarvest:'90',
    sowIndoor:null,          sowOutdoor:H('4-5'),      harv:H('5-10'),
    perennial:true, dormant:H('11-12,1-2'),
    good:['tomato','pea','cabbage'], bad:['chamomile'],
    notes:'INVASIVE — grow in containers! Repels many pests.' },
  { id:'chive',         name:'Chives',           emoji:'🌿', cat:'herb',      spacing:'20×20', cellsNeeded:1, sun:'full',    water:'medium', height:'low',   daysToHarvest:'80–90',
    sowIndoor:H('3-4'),      sowOutdoor:H('4-5'),      harv:H('4-10'),
    perennial:true, dormant:H('12,1-2'),
    good:['carrot','tomato','strawberry'], bad:['pea','bean_bush'],
    notes:'Perennial. Repels aphids and Japanese beetles. Edible flowers.' },
  { id:'lavender',      name:'Lavender',         emoji:'💜', cat:'herb',      spacing:'60×60', cellsNeeded:1, sun:'full',    water:'low',    height:'medium',daysToHarvest:'90',
    sowIndoor:null,          sowOutdoor:H('4-5'),      harv:H('6-8'),
    perennial:true, dormant:H('12,1'),
    good:['tomato','sage'], bad:[],
    notes:'Perennial. Attracts pollinators. Drought-tolerant once established.' },
  { id:'lemon_balm',    name:'Lemon Balm',       emoji:'🌿', cat:'herb',      spacing:'40×40', cellsNeeded:1, sun:'partial', water:'medium', height:'medium',daysToHarvest:'70–80',
    sowIndoor:H('3-4'),      sowOutdoor:H('4-5'),      harv:H('5-9'),
    perennial:true, dormant:H('11-12,1-2'),
    good:['tomato','squash','pumpkin'], bad:['mint'],
    notes:'Can spread aggressively. Attracts pollinators. Great tea plant.' },

  // ── FRUITS ──
  { id:'strawberry',    name:'Strawberry',       emoji:'🍓', cat:'fruit',     spacing:'30×30', cellsNeeded:1, sun:'full',    water:'medium', height:'low',   daysToHarvest:'90',
    sowIndoor:null,          sowOutdoor:H('3-4,8-9'),  harv:H('5-7'),
    perennial:true, dormant:H('11-12,1-2'),
    good:['lettuce','spinach','thyme','borage','bean_bush'], bad:['cabbage','broccoli','cauliflower','kale'],
    notes:'Perennial. Remove runners to encourage fruiting. Mulch to prevent rot.' },
  { id:'watermelon',    name:'Watermelon',       emoji:'🍉', cat:'fruit',     spacing:'150×150',cellsNeeded:4,sun:'full',    water:'medium', height:'vine',  daysToHarvest:'70–90',
    sowIndoor:H('4-5'),      sowOutdoor:H('5-6'),      harv:H('8-9'),
    good:['radish','marigold','nasturtium'], bad:['potato','cucumber'],
    notes:'Needs 80+ days of warm weather. Hollow thump = ripe.' },
  { id:'melon',         name:'Melon',            emoji:'🍈', cat:'fruit',     spacing:'100×100',cellsNeeded:4, sun:'full',    water:'medium', height:'vine',  daysToHarvest:'70–90',
    sowIndoor:H('4-5'),      sowOutdoor:H('5-6'),      harv:H('8-9'),
    good:['corn','bean_bush','radish','nasturtium'], bad:['potato'],
    notes:'Needs warm conditions — greenhouse or polytunnel in UK. Restrict to 4 fruits per plant for best size.' },
  { id:'raspberry',     name:'Raspberry',        emoji:'🍓', cat:'fruit',     spacing:'50×50', rowSpacing:150,cellsNeeded:1, sun:'full',    water:'medium', height:'tall',  daysToHarvest:'365+',
    sowIndoor:null,          sowOutdoor:H('11-12,2-3'),harv:H('6-10'),
    perennial:true, dormant:H('11-12,1-2'),
    good:['marigold','nasturtium','bean_bush'], bad:['potato'],
    notes:'Perennial. Plant bare-root canes Nov–Mar. Summer varieties fruit on last year\'s canes; autumn varieties on new canes.' },
  { id:'rhubarb',       name:'Rhubarb',          emoji:'🌱', cat:'fruit',     spacing:'90×90', cellsNeeded:4,  sun:'partial', water:'medium', height:'tall',  daysToHarvest:'365+',
    sowIndoor:null,          sowOutdoor:H('2-3,10-11'),harv:H('4-6'),
    perennial:true, dormant:H('9-12,1-2'),
    good:['onion','garlic','cabbage','kale'], bad:[],
    notes:'Perennial crown plant. Do not harvest in first year. Stalks only — leaves are toxic. Force early crops by covering with a pot in late winter.' },

  // ── FLOWERS ──
  { id:'marigold',      name:'Marigold',         emoji:'🌼', cat:'flower',    spacing:'25×25', cellsNeeded:1, sun:'full',    water:'low',    height:'low',   daysToHarvest:'50–55',
    sowIndoor:H('3-4'),      sowOutdoor:H('4-5'),      harv:H('6-10'),
    good:['tomato','pepper','squash','eggplant','potato','asparagus'], bad:['bean_bush'],
    notes:'Repels nematodes, aphids, whiteflies. Plant throughout the garden!' },
  { id:'nasturtium',    name:'Nasturtium',       emoji:'🌸', cat:'flower',    spacing:'30×30', cellsNeeded:1, sun:'full',    water:'low',    height:'low',   daysToHarvest:'50–60',
    sowIndoor:null,          sowOutdoor:H('4-5'),      harv:H('6-10'),
    good:['cucumber','squash','tomato','bean_bush','broccoli','radish'], bad:[],
    notes:'All parts edible! Repels aphids. Trap crop for aphids.' },
  { id:'sunflower',     name:'Sunflower',        emoji:'🌻', cat:'flower',    spacing:'50×50', cellsNeeded:1, sun:'full',    water:'low',    height:'tall',  daysToHarvest:'70–100',
    sowIndoor:null,          sowOutdoor:H('4-5'),      harv:H('8-10'),
    good:['cucumber','corn','squash'], bad:['potato','bean_bush'],
    notes:'Attracts pollinators. Plant at north end to avoid shading.' },
  { id:'zinnia',        name:'Zinnia',           emoji:'🌸', cat:'flower',    spacing:'30×30', cellsNeeded:1, sun:'full',    water:'low',    height:'medium',daysToHarvest:'60–70',
    sowIndoor:H('4-5'),      sowOutdoor:H('5'),        harv:H('6-10'),
    good:['tomato','cucumber','bean_bush','squash'], bad:[],
    notes:'Attracts butterflies and pollinators. Deadhead for continuous blooms.' },
  { id:'borage',        name:'Borage',           emoji:'🌸', cat:'flower',    spacing:'40×40', cellsNeeded:1, sun:'full',    water:'low',    height:'medium',daysToHarvest:'50–60',
    sowIndoor:null,          sowOutdoor:H('4-5'),      harv:H('6-9'),
    good:['tomato','squash','strawberry','cucumber'], bad:[],
    notes:'Edible blue flowers! Repels tomato hornworm. Self-seeds prolifically.' },
  { id:'calendula',     name:'Calendula',        emoji:'🌼', cat:'flower',    spacing:'25×25', cellsNeeded:1, sun:'full',    water:'low',    height:'low',   daysToHarvest:'45–60',
    sowIndoor:H('3-4,8-9'),  sowOutdoor:H('4,9'),      harv:H('5-10'),
    good:['tomato','asparagus','carrot','pea'], bad:[],
    notes:'Edible flowers. Medicinal. Repels aphids and attracts hoverflies.' },
  { id:'chamomile',     name:'Chamomile',        emoji:'🌼', cat:'flower',    spacing:'25×25', cellsNeeded:1, sun:'full',    water:'low',    height:'low',   daysToHarvest:'60',
    sowIndoor:null,          sowOutdoor:H('3-4'),      harv:H('6-8'),
    good:['cabbage','onion','cucumber','bean_bush'], bad:['mint'],
    notes:'Herbal tea plant. Self-seeds. Improves neighbouring plants.' },
  { id:'__path__',      name:'Path',             emoji:'🟫', cat:'infrastructure', spacing:'25×25', _isPath:true, sun:null, water:null, height:null, daysToHarvest:null,
    sowIndoor:null, sowOutdoor:[], harv:[], good:[], bad:[],
    notes:'Non-growing walkway tile. Marks paths and access routes through the bed.' },
];

// Germination expectations (days) for built-in plants.
const GERMINATION_DEFAULTS = {
  tomato: [5, 10],
  cherry_tomato: [5, 10],
  pepper: [7, 21],
  hot_pepper: [7, 21],
  cucumber: [3, 10],
  zucchini: [4, 10],
  squash: [4, 10],
  pumpkin: [4, 10],
  lettuce: [2, 10],
  spinach: [5, 14],
  kale: [5, 10],
  arugula: [3, 7],
  carrot: [10, 21],
  radish: [3, 7],
  beet: [5, 10],
  broccoli: [5, 10],
  cauliflower: [5, 10],
  cabbage: [4, 10],
  onion: [7, 14],
  garlic: [7, 21],
  leek: [8, 14],
  bean_bush: [5, 10],
  bean_pole: [5, 10],
  pea: [7, 14],
  corn: [5, 10],
  potato: [10, 28],
  eggplant: [7, 14],
  asparagus: [14, 28],
  basil: [5, 10],
  parsley: [14, 28],
  cilantro: [7, 14],
  dill: [7, 14],
  fennel: [7, 14],
  rosemary: [14, 28],
  thyme: [10, 21],
  oregano: [7, 14],
  sage: [10, 21],
  mint: [7, 14],
  chive: [7, 14],
  lavender: [14, 28],
  lemon_balm: [7, 14],
  strawberry: [10, 28],
  watermelon: [4, 10],
  marigold: [5, 10],
  nasturtium: [7, 14],
  sunflower: [7, 14],
  zinnia: [5, 10],
  borage: [5, 14],
  calendula: [5, 14],
  chamomile: [7, 14],
  broad_bean: [7, 14],
  runner_bean: [5, 10],
  brussels_sprout: [5, 10],
  chard: [5, 14],
  celery: [14, 21],
  kohlrabi: [5, 10],
  mangetout: [7, 14],
  pak_choi: [4, 7],
  parsnip: [14, 28],
  shallot: [7, 14],
  sweet_potato: [0, 0],
  swede: [5, 10],
  turnip: [5, 10],
  melon: [5, 10],
  raspberry: [0, 0],
  rhubarb: [0, 0],
  __path__: [0, 0],
};

// Merge with user custom plants at runtime — see store.js

// ── Botanical families for crop rotation ────────────────────────────────────
// Each family key maps to an array of plant IDs that belong to it.
// Applied automatically to BUILTIN_PLANTS below.
const PLANT_FAMILIES = {
  solanaceae:    ['tomato','cherry_tomato','pepper','hot_pepper','eggplant','potato'],
  cucurbitaceae: ['cucumber','zucchini','squash','pumpkin','watermelon','melon'],
  brassicaceae:  ['kale','arugula','radish','broccoli','cauliflower','cabbage','brussels_sprout','kohlrabi','pak_choi','swede','turnip'],
  apiaceae:      ['carrot','parsley','cilantro','dill','fennel','celery','parsnip'],
  fabaceae:      ['bean_bush','bean_pole','pea','broad_bean','runner_bean','mangetout'],
  amaranthaceae: ['spinach','beet','chard'],
  allioideae:    ['onion','garlic','leek','chive','shallot'],
  poaceae:       ['corn'],
  lamiaceae:     ['basil','rosemary','thyme','oregano','sage','mint','lavender','lemon_balm'],
  asteraceae:    ['lettuce','marigold','zinnia','chamomile','calendula','sunflower'],
  asparagaceae:  ['asparagus'],
  rosaceae:      ['strawberry','raspberry'],
  polygonaceae:  ['rhubarb'],
  convolvulaceae:['sweet_potato'],
  boraginaceae:  ['borage'],
  tropaeolaceae: ['nasturtium'],
};

(function applyFamilies() {
  const byId = {};
  Object.entries(PLANT_FAMILIES).forEach(([fam, ids]) =>
    ids.forEach(id => { byId[id] = fam; })
  );
  BUILTIN_PLANTS.forEach(p => { if (!p.family) p.family = byId[p.id] || null; });
})();

(function applyGerminationDefaults() {
  BUILTIN_PLANTS.forEach(p => {
    const range = GERMINATION_DEFAULTS[p.id];
    if (!range) return;
    if (p.germinationDaysMin === undefined || p.germinationDaysMin === null) p.germinationDaysMin = range[0];
    if (p.germinationDaysMax === undefined || p.germinationDaysMax === null) p.germinationDaysMax = range[1];
  });
})();
